name: Sync to S3
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure
      with:
        aws-access-key-id: ${{ AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  
    
    - name: Sync to S3
      run: aws s3 sync . s3://s3forlambdafuntions/csvfile/
